language: python

python:

  - "3.6"

# command to install dependencies

install:

    - pip install geatpy

# command to run tests, we only need to test the installation so that we do nothing here.

script:

    - 
