language: python

python:

  - "3.5"

script:

    pip install geatpy==2.1.0rc1
    
    python test/installation_test.py
    
    pip uninstall geatpy -y
    
    python setup.py install
    
    python test/installation_test.py
