language: python

python:

  - "3.5"

# command to install dependencies

install:
    
  # needn't to do anything.
  
# command to run tests, we have done other tests so that we do nothing here.

script:

    - 
