language: python

python:

  - "3.5"

# command to install dependencies

install:

  pip install geatpy
  
# command to run tests, we have done other tests so that we do nothing here.

script:

    import geatpy as ea
